# Copyright (c) 2010 David Bender assigned to Benegon Enterprises LLC
# See the file LICENSE for full license information.

Import('*')

posix = bin_env.StaticObject("posix.cpp");

step = bin_env.Program("step", Split('stepbystep.c'), LIBS=Split("benejson m stdc++"));
json = bin_env.Program("jsontest", Split('jsontest.c'), LIBS=Split("benejson m stdc++"));
jbuff = bin_env.Program("jbuff", Split('jsonbuff.c'), LIBS=Split("benejson m stdc++"));
strtest = bin_env.Program("strtest", Split('strtest.c'), LIBS=Split("benejson m stdc++"));
verify = bin_env.Program("verify", Split('verify.c'), LIBS=Split("benejson m stdc++"));
jsonoise = bin_env.Program("jsonoise", Split('jsonoise.c'));

negative_test = bin_env.Program("negative_test", source = [posix, "all_negatives.cpp"], LIBS=Split("benejson m"));

pulltest = bin_env.Program("pulltest", source = [posix, "pulltest.cpp"], LIBS=Split("benejson m"));

spam = bin_env.Program("spam", source = [posix, "spam.cpp"], LIBS=Split("benejson m"));

jsontool = bin_env.Program("jsontool", source = ["jsontool.c"], LIBS=Split("benejson m stdc++"));

jsongrab = bin_env.Program("jsongrab", source = [posix, "jsongrab.cpp"], LIBS=Split("benejson m"));

bin_env.Install(bin_env.BinDest, step)
bin_env.Install(bin_env.BinDest, json)
bin_env.Install(bin_env.BinDest, jbuff)
bin_env.Install(bin_env.BinDest, negative_test)
bin_env.Install(bin_env.BinDest, pulltest)
bin_env.Install(bin_env.BinDest, strtest)
bin_env.Install(bin_env.BinDest, spam)
bin_env.Install(bin_env.BinDest, jsontool)
bin_env.Install(bin_env.BinDest, verify)
bin_env.Install(bin_env.BinDest, jsonoise)
bin_env.Install(bin_env.BinDest, jsongrab)
