# Copyright (c) 2010 David Bender assigned to Benegon Enterprises LLC
# See the file LICENSE for full license information.

Import('*')

lib_env = lib_env.Clone()

lstatic = lib_env.StaticLibrary('benejson', Split('benejson.c pull.cpp memreader.cpp'))
lt = lib_env.SharedLibrary('benejson', Split('benejson.c pull.cpp memreader.cpp'))
lib_env.Install(bin_env.LibDest, [lt, lstatic])
lib_env.Install(lib_env.IncDest + "/benejson", Split('benejson.h pull.hh memreader.hh'))
