# Copyright (c) 2010 David Bender assigned to Benegon Enterprises LLC
# See the file LICENSE for full license information.

Import('*')

lib_env = lib_env.Clone()

# Check for presence of stpcpy
conf = Configure(lib_env)

if not conf.CheckFunc("stpcpy"):
	print("Did not find stpcpy(), using bnj local version")
	conf.env.Append(CPPDEFINES = ["-Dstpcpy=bnj_local_stpcpy"])

if not conf.CheckFunc("stpncpy"):
	print("Did not find stpncpy(), using bnj local version")
	conf.env.Append(CPPDEFINES = ["-Dstpncpy=bnj_local_stpncpy"])
lib_env = conf.Finish()

# Helps windows/mingw get the medicine down
lib_env["WINDOWS_INSERT_DEF"] = 1

lstatic = lib_env.StaticLibrary('benejson', Split('benejson.c pull.cpp'))
lt = lib_env.SharedLibrary('benejson', Split('benejson.c pull.cpp'))
lib_env.Install(bin_env.LibDest, [lt, lstatic])
lib_env.Install(lib_env.IncDest + "/benejson", Split('benejson.h pull.hh'))
